image: alpine:latest

stages:
  - build
  - test
  - deploy

.default_rules: &default_rules
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feat-ci"

build-job:
  <<: *default_rules
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"

test-job:
  <<: *default_rules
  stage: test
  image: node:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - echo "Running test..."
    - npm install
    - npm test
  when: on_success

deploy-job:
  <<: *default_rules
  stage: deploy
  image: alpine/helm:latest
  script: # Use Helm to deploy the backend
    - echo "Deploying application with Helm..."
    - |
      helm upgrade --install scalyshop-backend ./scalyshop-backend \
        --set image.repository=$CI_REGISTRY_IMAGE \
        --set image.tag=$CI_COMMIT_SHA \
        --namespace scalyshop \
        --wait --timeout 300s --debug
  when: on_success
