apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: scalyshop
  name: gitlab-runner
rules:
- apiGroups: [""] # indicates the core API group
  resources: ["pods", "services", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
  #kubectl create rolebinding --namespace=scalyshop scalyshop-binding --role=gitlab-runner --serviceaccount=scalyshop:default