global:
  security:
    ## @param global.security.allowInsecureImages Allows skipping image verification
    allowInsecureImages: true
image:
  registry: docker.io
  repository: dlavrenuek/bitnami-mongodb-arm
  tag: "8.0.4"

auth:
  enabled: true
  username: scaly
  password: scalypw
  database: scalyDB