gitlabUrl: https://git.chalmers.se
runnerToken: "glrt-t2_Brh1GCFkQXJrsen7i7ig"

rbac:
  create: true

serviceAccount:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["list", "get", "watch", "create", "delete"]
    - apiGroups: [""]
      resources: ["pods/exec"]
      verbs: ["create"]
    - apiGroups: [""]
      resources: ["pods/log"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["pods/attach"]
      verbs: ["list", "get", "create", "delete", "update"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["list", "get", "create", "delete", "update"]
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["list", "get", "create", "delete", "update"]


runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        privileged = true
        helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:arm64-v17.8.3"

concurrent: 3  # Increase to allow more jobs to run simultaneously

#helm install --namespace scalyshop gitlab-runner -f runner-values.yaml gitlab/gitlab-runner

#kubectl create rolebinding --namespace=scalyshop scalyshop-binding --role=gitlab-runner --serviceaccount=scalyshop:default