gitlabUrl: https://git.chalmers.se
runnerToken: "glrt-t2_Brh1GCFkQXJrsen7i7ig"

#rbac:
#    create: true

runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        privileged = true
        helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:arm64-v17.8.3"

concurrent: 3  # Increase to allow more jobs to run simultaneously

#helm install --namespace scalyshop gitlab-runner -f runner-values.yaml gitlab/gitlab-runner

#kubectl create rolebinding --namespace=scalyshop scalyshop-binding --role=gitlab-runner --serviceaccount=scalyshop:default