apiVersion: v1
kind: Service
metadata:
  name: scalyshop-v2-backend-service
  labels:
    app: ss-backend
spec:
  type: LoadBalancer
  selector:
    app: ss-backend
  ports:
    - port: 80
      targetPort: 5045